<?php

namespace MailBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUserByName($name)
    {
        $dql = "SELECT b FROM MailBoxBundle:User b WHERE b.name LIKE :nameToFind";

        $query = $this->getEntityManager()->createQuery($dql)->setParameter('nameToFind', $name);

        return $query->getResult();
    }

    public function findUserBySurname($name)
    {
        $dql = "SELECT b FROM MailBoxBundle:User b WHERE b.surname LIKE :nameToFind";

        $query = $this->getEntityManager()->createQuery($dql)->setParameter('nameToFind', $name);

        return $query->getResult();
    }
}
